In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
arr=np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr1=np.array([[1,2,3],[2,3,4]])

In [11]:
# To check the dimention of the array
arr.ndim

1

In [10]:
arr1.ndim

2

In [12]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
mat=np.matrix(l)

In [22]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [23]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [24]:
arr

array([1, 2, 3, 4, 5])

In [25]:
a= arr

In [26]:
a

array([1, 2, 3, 4, 5])

In [29]:
## Changing the data in arr array
arr[0]=100

In [30]:
arr

array([100,   2,   3,   4,   5])

In [34]:
## Deep Copy
b= np.copy(arr)

In [35]:
b[0]=234

In [36]:
b[0]

234

In [37]:
arr

array([100,   2,   3,   4,   5])

In [39]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [40]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [42]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [43]:
iterable = (i*i for i in range(5))

In [44]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [45]:
np.fromstring('23 45 56', sep =' ')

array([23., 45., 56.])

In [46]:
np.fromstring('23,45,56', sep =',')

array([23., 45., 56.])

In [47]:
arr

array([100,   2,   3,   4,   5])

In [48]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [50]:
# TO print the dimention of array
arr1.ndim

2

In [55]:
# To print the size of array(total number of elements in the array
arr.size

5

In [56]:
arr1.size

6

In [58]:
# To print the shape of the array
arr.shape

(5,)

In [59]:
arr1.shape

(2, 3)

In [60]:
arr.dtype

dtype('int64')

In [61]:
arr1.dtype

dtype('int64')