In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list (range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

### Alternate of Range function 'arange'  where we can generate even floating numbers.

In [6]:
np.arange(.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
## Equally divide into 20 data sets
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
arr=np.ones((3,4))

In [17]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
arr1=np.eye(5)

In [26]:
import pandas as pd

In [27]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [28]:
np.random.rand(2,3)

array([[0.52778344, 0.63237192, 0.64255116],
       [0.05639727, 0.96178289, 0.90929676]])

In [29]:
np.random.randn(2,3)

array([[ 1.42860785, -0.4982937 , -0.1231796 ],
       [ 1.20321432,  1.38584601,  0.30696623]])

In [34]:
arr2=np.random.randint(1,5,(3,4))

In [35]:
arr2

array([[1, 1, 1, 2],
       [3, 1, 2, 3],
       [2, 3, 2, 4]])

In [36]:
arr2.size 

12

In [37]:
arr2.shape

(3, 4)

In [38]:
arr2.reshape(6,2)

array([[1, 1],
       [1, 2],
       [3, 1],
       [2, 3],
       [2, 3],
       [2, 4]])

In [40]:
arr2.reshape(2,6)

array([[1, 1, 1, 2, 3, 1],
       [2, 3, 2, 3, 2, 4]])

In [42]:
arr2.reshape(2,2,3)

array([[[1, 1, 1],
        [2, 3, 1]],

       [[2, 3, 2],
        [3, 2, 4]]])

In [44]:
arr1=np.random.randint(1,10,(5,6))

In [45]:
arr1

array([[7, 4, 1, 3, 9, 4],
       [8, 5, 8, 7, 2, 8],
       [6, 5, 4, 1, 7, 3],
       [2, 5, 5, 1, 5, 1],
       [4, 5, 5, 2, 8, 9]])

In [46]:
arr1>8

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False,  True]])

### To filter out the data from array matrix

In [53]:
arr1[arr1>8]

array([9, 9])

In [54]:
arr1

array([[7, 4, 1, 3, 9, 4],
       [8, 5, 8, 7, 2, 8],
       [6, 5, 4, 1, 7, 3],
       [2, 5, 5, 1, 5, 1],
       [4, 5, 5, 2, 8, 9]])

### To extract particular data in the Array Matrix

In [55]:
arr1[0,[0,1]]

array([7, 4])

In [56]:
arr1[2:4,[2,3]]

array([[4, 1],
       [5, 1]])

In [57]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [58]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [59]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 2]])

### Here we are adding two matrices

In [60]:
arr1+arr2

array([[2, 4, 2],
       [2, 3, 3],
       [3, 3, 4]])

### Here we are substracting two matrices

In [61]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0,  1,  1],
       [-1,  1,  0]])

### Using '*' we can multiply two matrices simply

In [62]:
arr1*arr2

array([[1, 4, 1],
       [1, 2, 2],
       [2, 2, 4]])

### Using '@' we can do matrix multiplication

In [64]:
arr1@arr2

array([[5, 5, 5],
       [7, 6, 7],
       [7, 6, 7]])

In [65]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 2. , 2. ],
       [0.5, 2. , 1. ]])

### Numpy - Broadcasting:

In [67]:
arr= np.zeros((3,4))

In [68]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [70]:
a= np.array([1,2,3,4])

In [71]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [75]:
b= np.array([[3,4,5]])

In [78]:
arr1=arr+b.T

In [77]:
b.T

array([[3],
       [4],
       [5]])

In [79]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [80]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [81]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [82]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [85]:
## To extract minimum element in the Array Matrix
np.min(arr1)

3.0

In [86]:
## To Extract maximum element in the array Matrix
np.max(arr1)

5.0