In [2]:
import numpy as np

## Numpy - Array Manipulation

In [4]:
arr=np.random.randint(1,10,(4,4))

In [5]:
arr

array([[5, 8, 8, 2],
       [2, 5, 9, 3],
       [8, 6, 6, 7],
       [4, 1, 4, 6]])

In [6]:
arr.reshape(8,2)

array([[5, 8],
       [8, 2],
       [2, 5],
       [9, 3],
       [8, 6],
       [6, 7],
       [4, 1],
       [4, 6]])

In [7]:
arr

array([[5, 8, 8, 2],
       [2, 5, 9, 3],
       [8, 6, 6, 7],
       [4, 1, 4, 6]])

In [9]:
## If i have to rotate this array
arr.T

array([[5, 2, 8, 4],
       [8, 5, 6, 1],
       [8, 9, 6, 4],
       [2, 3, 7, 6]])

In [11]:
## To convert it into one dimentional array
arr.flatten()

array([5, 8, 8, 2, 2, 5, 9, 3, 8, 6, 6, 7, 4, 1, 4, 6])

In [13]:
## Expanding dimention of the array
np.expand_dims(arr,axis=1)

array([[[5, 8, 8, 2]],

       [[2, 5, 9, 3]],

       [[8, 6, 6, 7]],

       [[4, 1, 4, 6]]])

In [15]:
data= np.array([[1],[2],[3]])

In [18]:
## For squeezing the array we use squeeze method of numpy
np.squeeze(data)

array([1, 2, 3])

In [21]:
## To repeat the occurance of elements in the array
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [23]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [24]:
np.diag(np.array([1,2,3,4]))    

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Numpy- Binary Operations.

In [26]:
arr1= np.random.randint(1,10,(3,4))
arr2= np.random.randint(1,10,(3,4))

In [27]:
arr1

array([[7, 2, 5, 5],
       [9, 6, 5, 4],
       [9, 6, 8, 6]])

In [28]:
arr2

array([[5, 2, 9, 8],
       [1, 3, 2, 6],
       [3, 7, 7, 6]])

In [31]:
arr1**arr2

array([[  16807,       4, 1953125,  390625],
       [      9,     216,      25,    4096],
       [    729,  279936, 2097152,   46656]])

In [32]:
~arr1

array([[ -8,  -3,  -6,  -6],
       [-10,  -7,  -6,  -5],
       [-10,  -7,  -9,  -7]])

In [33]:
arr1>arr2

array([[ True, False, False, False],
       [ True,  True,  True, False],
       [ True, False,  True, False]])

## Numpy- String Functions

In [35]:
arr= np.array(["sudh","kumar"])

In [36]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

## Numpy -  Mathematical Functions

In [40]:
arr1

array([[7, 2, 5, 5],
       [9, 6, 5, 4],
       [9, 6, 8, 6]])

In [41]:
np.sin(arr1)

array([[ 0.6569866 ,  0.90929743, -0.95892427, -0.95892427],
       [ 0.41211849, -0.2794155 , -0.95892427, -0.7568025 ],
       [ 0.41211849, -0.2794155 ,  0.98935825, -0.2794155 ]])

In [42]:
np.cos(arr1)

array([[ 0.75390225, -0.41614684,  0.28366219,  0.28366219],
       [-0.91113026,  0.96017029,  0.28366219, -0.65364362],
       [-0.91113026,  0.96017029, -0.14550003,  0.96017029]])

In [43]:
np.tan(arr1)

array([[ 0.87144798, -2.18503986, -3.38051501, -3.38051501],
       [-0.45231566, -0.29100619, -3.38051501,  1.15782128],
       [-0.45231566, -0.29100619, -6.79971146, -0.29100619]])

In [44]:
np.log10(arr1)

array([[0.84509804, 0.30103   , 0.69897   , 0.69897   ],
       [0.95424251, 0.77815125, 0.69897   , 0.60205999],
       [0.95424251, 0.77815125, 0.90308999, 0.77815125]])

In [45]:
np.exp(arr1)

array([[1.09663316e+03, 7.38905610e+00, 1.48413159e+02, 1.48413159e+02],
       [8.10308393e+03, 4.03428793e+02, 1.48413159e+02, 5.45981500e+01],
       [8.10308393e+03, 4.03428793e+02, 2.98095799e+03, 4.03428793e+02]])

In [47]:
np.power(arr1,2)

array([[49,  4, 25, 25],
       [81, 36, 25, 16],
       [81, 36, 64, 36]])

In [48]:
np.mean(arr1)

6.0

In [49]:
np.median(arr1)

6.0

In [50]:
np.std(arr1)

1.9578900207451218

In [51]:
np.var(arr1)

3.8333333333333335

In [52]:
np.max(arr1)

9

## Numpy -  Arithmetic Operations

In [53]:
arr1

array([[7, 2, 5, 5],
       [9, 6, 5, 4],
       [9, 6, 8, 6]])

In [54]:
arr1 - arr2

array([[ 2,  0, -4, -3],
       [ 8,  3,  3, -2],
       [ 6, -1,  1,  0]])

In [55]:
np.subtract(arr1,arr2)

array([[ 2,  0, -4, -3],
       [ 8,  3,  3, -2],
       [ 6, -1,  1,  0]])

In [56]:
np.multiply(arr1,arr2)

array([[35,  4, 45, 40],
       [ 9, 18, 10, 24],
       [27, 42, 56, 36]])

In [57]:
np.mod(arr1,arr2)

array([[2, 0, 5, 5],
       [0, 0, 1, 4],
       [0, 6, 1, 0]])

In [58]:
np.power(arr1,arr2)

array([[  16807,       4, 1953125,  390625],
       [      9,     216,      25,    4096],
       [    729,  279936, 2097152,   46656]])

In [59]:
np.sqrt(arr1)

array([[2.64575131, 1.41421356, 2.23606798, 2.23606798],
       [3.        , 2.44948974, 2.23606798, 2.        ],
       [3.        , 2.44948974, 2.82842712, 2.44948974]])

## Numpy - Statistical Functions

In [60]:
arr1

array([[7, 2, 5, 5],
       [9, 6, 5, 4],
       [9, 6, 8, 6]])

In [61]:
np.mean(arr1)

6.0

In [62]:
np.std(arr1)

1.9578900207451218

In [63]:
np.median(arr1)

6.0