## Numpy - Sort, search and counting functions

In [1]:
import numpy as np

In [7]:
arr=np.array([4,2,8,1,5,23])

In [8]:
arr

array([ 4,  2,  8,  1,  5, 23])

In [9]:
np.sort(arr)

array([ 1,  2,  4,  5,  8, 23])

In [10]:
np.searchsorted(arr,6)

5

In [11]:
arr1=np.array([0,324,645,65,2,3,12,23])

In [12]:
np.count_nonzero(arr1)

7

In [14]:
## At what indices data is greater than zero
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 6, 7]),)

In [18]:
np.extract (arr1>2,arr1)

array([324, 645,  65,   3,  12,  23])

## Numpy - Byte Swapping

In [19]:
arr1

array([  0, 324, 645,  65,   2,   3,  12,  23])

In [42]:
## Represent data in byte format
arr.byteswap(True)

array([ 4,  2,  8,  1,  5, 23])

In [43]:
arr

array([ 4,  2,  8,  1,  5, 23])

## Numpy - Copies & Views

In [44]:
arr1

array([  0, 324, 645,  65,   2,   3,  12,  23])

In [45]:
a= np.copy(arr1)

In [46]:
b= arr.view()

In [47]:
b

array([ 4,  2,  8,  1,  5, 23])

In [48]:
b[0] = 234

In [49]:
b

array([234,   2,   8,   1,   5,  23])

In [50]:
arr

array([234,   2,   8,   1,   5,  23])

## Numpy - Matrix Library

In [51]:
import numpy.matlib as nm

In [52]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [53]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [54]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Numpy - Linerar Algebra

In [59]:
arr1=np.random.randint([[2,3],[4,5]])

In [60]:
arr2=np.random.randint([[5,3] , [2,5]])

In [61]:
arr1

array([[1, 1],
       [0, 0]])

In [62]:
arr2

array([[1, 2],
       [0, 1]])

In [63]:
np.dot(arr1,arr2)

array([[1, 3],
       [0, 0]])

In [64]:
arr1@arr2

array([[1, 3],
       [0, 0]])