## Consider the following code to answer the below questions

In [23]:
import numpy as np
list_1=['1','2','3','4','5']
array_list=np.array(object=list_1)

### Problem_1: Is there any difference in the data type of variable list_1 and array_list? If there is then write a code to print the data types of both the variable

  - Yes, there is difference between these two because list_1 is collection of items that can be different but the array_list is numpy array which is collection of item of same data type.

In [9]:
# Printing the data type of both the variables
print("Data type of list_1:",type(list_1))
print("Data type of array_list:",type(array_list))

Data type of list_1: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


### Problem_2: Write a code to print the data type of each and every element of both the variable list_1 and array_list.

In [14]:
# Printing the data type of each element in list_1
for element in list_1:
    print("Data type of Element of list_1:",type(element))
# Printing the data type of each element in array_list
for element in array_list:
    print("Data Type of Element of array_list:",type(element))

Data type of Element of list_1: <class 'str'>
Data type of Element of list_1: <class 'str'>
Data type of Element of list_1: <class 'str'>
Data type of Element of list_1: <class 'str'>
Data type of Element of list_1: <class 'str'>
Data Type of Element of array_list: <class 'numpy.str_'>
Data Type of Element of array_list: <class 'numpy.str_'>
Data Type of Element of array_list: <class 'numpy.str_'>
Data Type of Element of array_list: <class 'numpy.str_'>
Data Type of Element of array_list: <class 'numpy.str_'>


### Problem_3: Consider the following change in the variable, array_list:

In [24]:
array_list=np.array(object=list_1, dtype=int)

### will there be any difference in the data type of the elements present in both the variable, list_1 and array_list? If so then print the data type of each element present in both the variable, list_1 and array_list.

In [26]:
## YES! there is difference between both the variables. Element in list_1 are type of str and  element in array_list are type of numpy integers.


#Printing the data type of list_1:
for element in list_1:
    print(type(element))
    
#Printing the data type of array_list:
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Consider the below code to answer the further questions:

In [21]:
import numpy as np
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)

### Problem_4: Write a code to find the following characteristics of variable, num_array:
### (i) shapes
### (ii) size

In [7]:
# Printing the shape of num_array
print(np.shape(num_array))

(2, 3)


In [5]:
#Printing the size of num_array
print(np.size(num_array))

6


### Problem_5 Write a code to create a numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [13]:
zeros_matrix=np.zeros((3,3))
# Printing the matrix 3*3 containing zeros only
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Problem_6: Create an Identity matrix of shape(5,5) using numpy functions?

In [27]:
iden= np.identity(5)
# Printing the identity matrix
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
